name = "TensorToolbox"
uuid = "9c690861-8ade-587a-897e-15364bc6f718"
version = "1.0.1"
author = ["Lana Periša lana.perisa@fesb.hr"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "≥ 1.1.0"
